steps:
  - command: .buildkite/scripts/fake-test.sh
    label: ":coverage:"
  - wait
  - command: .buildkite/scripts/fake-deploy.sh
    label: ":cloudfoundry: pr"
    if: "!build.pull_request.draft"
  - command: .buildkite/scripts/fake-deploy.sh
    label: ":cloudfoundry: master"
    branches: "master"
