steps:
  - command: .buildkite/scripts/fake-test.sh
    label: ":coverage:"
  - command: buildkite-agent pipeline upload .buildkite/pipeline.pr.yml
    label: ":pipeline: pr"
    if: build.pull_request.repository != ""
  - command: buildkite-agent pipeline upload .buildkite/pipeline.deploy.yml
    label: ":pipeline: master"
    branches: "master"
  # TODO: how to report PR build error if its not against master?
  # - command: exit 1
  #   label: ":github: PR must be against master"
  #   if: "build.pull_request.repository && !build.pull_request.draft && build.pull_request.base_branch != 'master'"
