# NOTICE: this file is should not be dynamically loaded by "buildkite-agent pipeline upload",
#         instead, copy and paste this into buildkite.com Pipeline Settings as the Steps from YAML.
#         This will prevent a misadventurous commit from changing the initial pipeline against your will.
env:
  PR_WHITELIST: |
    github.com/starkandwayne/
    github.com/drnic/
    github.com/jhunt/
steps:
  - command: .buildkite/scripts/choose-pr-pipeline.sh | buildkite-agent pipeline upload
    label: ":pipeline: pr"
    if: build.pull_request.repository != null
  - command: buildkite-agent pipeline upload .buildkite/pipeline.master.yml
    label: ":pipeline: master"
    if: build.branch == 'master' && build.pull_request.repository == null
  - command: buildkite-agent pipeline upload .buildkite/pipeline.branch.yml
    label: ":pipeline: branch"
    if: build.branch != 'master' && build.pull_request.repository == null
