name: "buildkite-community-pr-flow-example"
description: "Whitelist or block community Pull Requests"
steps:
  - command: buildkite-agent pipeline upload .buildkite/pipeline.yml
    label: ":pipeline:"
